name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install wasm rust target
      run: rustup target add wasm32-unknown-unknown

    - name: Install Trunk
      run: cargo install --locked trunk

    - name: Build
      run: trunk build
      working-directory: ./frontend

    - name: Archive frontend artifacts
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/main'
      with:
        name: dist
        path: |
          frontend/dist
